mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('vjk.urls')),
	url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vjk/urls.py
from django.conf.urls import url

from . import views

app_name = 'vjk'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student-intake', views.student_form, name='studentform'),
    url(r'^success', views.success, name='success')
]

vjk/models.py
from django.db import models
from django.core.validators import RegexValidator

province_choices = {
	('AB','Alberta'),
	('BC','British Columbia'),
	('SK','Saskatchewan'),
	('MB','Manitoba'),
	('ON','Ontario'),
	('QC','Quebec'),
	('PE','Prince Edward Island'),
	('NS','Nova Scotia'),
	('NL','Newfoundland and Labrador'),
	('NB','New Brunswick'),
	('NT','Northwest Territories'),
	('NU','Nunavut'),
	('YT','Yukon')
}

phone_regex = RegexValidator(regex=r'^\+?1?\d{10,12}$',
				message="Phone number must be entered in the format: '+16045555555'.")



# Create your models here.
class Contact(models.Model):
	first_name 		= models.CharField(max_length = 75, verbose_name="First Name")
	last_name 		= models.CharField(max_length = 75, verbose_name="Last Name")
	email 			= models.EmailField(verbose_name="E-mail")
	phone_number 	= models.CharField(validators=[phone_regex],max_length = 12, blank=True, null=True, verbose_name="Phone")

	address_line1 	= models.CharField(max_length = 50, blank=True, null=True, verbose_name="Address - Line 1")
	address_line2 	= models.CharField(max_length = 50, blank=True, null=True, verbose_name="Address - Line 2")
	city 			= models.CharField(max_length = 30, blank=True, null=True, verbose_name="City")
	province 		= models.CharField(max_length = 20, choices = province_choices, blank=True, null=True, verbose_name="Province")
	postal_code 	= models.CharField(max_length=6, blank=True, null=True, verbose_name="Postal Code")

	# Return name as identifier
	def __str__(self):
		return self.first_name + ' ' + self.last_name

	# Iterate over fields values. 
	def __iter__(self):
		for field in self._meta.fields:
			if field.name != "id":
				yield field.value_to_string(self)

	# Enforce that first name, last name and email form unique combination
	class meta:
		unique_together = (('first_name', 'last_name', 'email'),)
	
	def organization(self):
		"""
		Return donor(s) or sponsor(s) for which contact is the contact
		"""
		result = ''
		d1,d2 = self.donor1.first(), self.donor2.first()
		s1,s2 = self.sponsor1.first(), self.sponsor2.first()

		if d1:
			result += d1.org_name
		if d2:
			result += ' and ' + d2.org_name if d1 else d2.org_name
		if s1:
			result += ' and ' + s1.name if d1 or d2 else s1.name
		if s2:
			result += ' and ' + s2.name if d1 or d2 or s1 else s2.name
		return result
		organization.short_description = "Contact For?"

class Donor(models.Model):
	org_name 			= models.CharField(max_length = 50, verbose_name="Organization Name")
	location 			= models.CharField(max_length = 100, blank=True, null=True, verbose_name="Location")
	year_donation 		= models.IntegerField(verbose_name="Year", blank=True, null=True)
	amount_donation 	= models.IntegerField(verbose_name="Amount Donated", blank=True, null=True)
	primary_contact 	= models.ForeignKey(Contact,
								on_delete=models.PROTECT,
								related_name="donor1",
								blank=True, null=True,
								verbose_name="Primary Contact")
	secondary_contact 	= models.ForeignKey(Contact,
								on_delete=models.PROTECT,
								related_name="donor2",
								blank=True, null=True,
								verbose_name="Secondary Contact")

	# Return name as identifier
	def __str__(self):
		return self.org_name

	# Iterate over fields values. If foreign key, produce name instead of id
	def __iter__(self):
		for field in self._meta.fields:
			if field.name != "id":
				val = field.value_to_string(self)
				if (val != 'None' 
					and (field.name == 'primary_contact' 
						or field.name == 'secondary_contact')):
					yield Contact.objects.get(pk=int(val))
				else:
					yield val

	# Organisation name is unique
	class meta:
		unique_together = (('org_name'),)


class Sponsor(models.Model):
	name 				= models.CharField(max_length = 50, verbose_name="Name")
	service_provided 	= models.CharField(max_length = 50, blank=True, null=True, verbose_name="Service Provided")
	primary_contact 	= models.ForeignKey(Contact,
								on_delete=models.PROTECT,
								related_name="sponsor1",
								default=-1,
								blank=True, null=True,
								verbose_name="Primary Contact")
	secondary_contact 	= models.ForeignKey(Contact,
								on_delete=models.PROTECT,
								related_name="sponsor2",
								default=-1,
								blank=True, null=True,
								verbose_name="Secondary Contact")

	# Return name as identifier
	def __str__(self):
		return self.name

	# Iterate over fields values. If foreign key, produce name instead of id
	def __iter__(self):
		for field in self._meta.fields:
			if field.name != "id":
				val = field.value_to_string(self)
				if (val != 'None' 
					and (field.name == 'primary_contact' 
						or field.name == 'secondary_contact')):
					yield Contact.objects.get(pk=int(val))
				else:
					yield val

	# Name of sponsor is unique
	class meta:
		unique_together = (('name'),)



class Student(models.Model):
	first_name 			= models.CharField(max_length = 75, verbose_name="First Name")
	last_name 			= models.CharField(max_length = 75, verbose_name="Last Name")
	gender 				= models.CharField(max_length = 10, 
											choices = {
														('M','Male'),
														('F','Female'),
														('O','Other')
													}, 
											verbose_name="Gender", null = True, blank = True)
	
	bday_regex 			= RegexValidator(regex=r'^\d{2}/\d{2}/\d{4}', 
								message='Birth date must be entered in form MM/DD/YYYY')
	birth_date 			= models.CharField(max_length = 10, validators=[bday_regex], blank = True, null = True, verbose_name='Birth Date (MM/DD/YYYY)')
	
	aboriginal_group 	= models.CharField(max_length = 20, 
											choices = 	{
											('First Nations','First Nations'),
											('Metis','Metis'),
											('Inuit','Inuit')
											},
											blank = True, null = True, 
											verbose_name='Aboriginal Group')

	email 				= models.EmailField(verbose_name="E-mail")
	school 				= models.CharField(max_length = 75, blank=True, null=True, verbose_name="School")
	home_phone 			= models.CharField(max_length = 12, validators = [phone_regex], blank=True, null=True, verbose_name="Home Phone")
	cell_phone	 		= models.CharField(max_length = 12, validators = [phone_regex], blank=True, null=True, verbose_name="Cell Phone")

	guardian_fname		= models.CharField(max_length = 75, verbose_name="Guard. First Name", blank = True, null = True)
	guardian_lname		= models.CharField(max_length = 75, verbose_name="Guard. Last Name", blank = True, null = True)
	guardian_phone		= models.CharField(max_length = 12, validators = [phone_regex], blank=True, null=True, verbose_name="Guard. Phone")
	guardian_email		= models.EmailField(default="",verbose_name="Guard. Email",blank=True,null=True)

	teacher_fname		= models.CharField(max_length = 75, verbose_name="Teach. First Name", blank = True, null = True)
	teacher_lname		= models.CharField(max_length = 75, verbose_name="Teach. Last Name", blank = True, null = True)
	teacher_email		= models.EmailField(default="",verbose_name="Teach. Email",blank=True,null=True)
	teacher_phone		= models.CharField(max_length = 12, validators = [phone_regex], blank=True, null=True, verbose_name="Teach. Phone")
	
	program_city 		= models.CharField(max_length = 100, blank=True, null=True, verbose_name="Program City")
	year_attended 		= models.IntegerField(blank=True,null=True, verbose_name="Year Attended")
	program_institution = models.CharField(max_length = 75, blank=True, null=True, verbose_name="Institution")
	mentor				= models.CharField(max_length = 75, blank=True, null=True, verbose_name="Mentor")
	room_assignment		= models.CharField(max_length = 75, blank=True, null=True, verbose_name="Room Assign.")
	chaperone_fname		= models.CharField(max_length = 75, blank=True, null=True, verbose_name="Chaperone First Name")
	chaperone_lname		= models.CharField(max_length = 75, blank=True, null=True, verbose_name="Chaperone Last Name")

	address_line1 		= models.CharField(max_length = 50, blank=True, null=True, verbose_name="Address - Line 1")
	address_line2 		= models.CharField(max_length = 50, blank=True, null=True, verbose_name="Address - Line 2")
	city 				= models.CharField(max_length = 30, blank=True, null=True, verbose_name="City")
	province 			= models.CharField(max_length = 20, choices = province_choices, blank=True, null=True, verbose_name="Province")
	postal_code 		= models.CharField(max_length=6, blank=True, null=True, verbose_name="Postal Code")

	reference_fname 	= models.CharField(max_length=75,default="", verbose_name="Ref. First Name")
	reference_lname 	= models.CharField(max_length=75,default="", verbose_name="Ref. Last Name")
	reference_email 	= models.EmailField(default="", verbose_name='Ref. E-mail')
	reference_number 	= models.CharField(max_length = 12, validators = [phone_regex], blank=True, null=True, verbose_name="Ref. Number")

	reference_address_line1 = models.CharField(max_length = 50, blank=True, null=True, verbose_name="Ref. Addr - Line 1")
	reference_address_line2 = models.CharField(max_length = 50, blank=True, null=True, verbose_name="Ref. Addr - Line 2")
	reference_city 			= models.CharField(max_length = 30, blank=True, null=True, verbose_name="Ref. City")
	reference_province 		= models.CharField(max_length = 20, choices = province_choices, blank=True, null=True, verbose_name="Ref. Province")
	reference_postal_code 	= models.CharField(max_length=6, blank=True, null=True, verbose_name="Ref. Postal Code")

	# Return name as identifier
	def __str__(self):
		return self.first_name + ' ' + self.last_name

	# Iterate over field values
	def __iter__(self):
		for field in self._meta.fields:
			if field.name != "id":
				yield field.value_to_string(self)

	# Enforce that first name, last name and email form unique combination
	class meta:
		unique_together = (('first_name', 'last_name', 'email'),)

class Volunteer(models.Model):

	first_name 			= models.CharField(max_length = 75, verbose_name="First Name")
	last_name 			= models.CharField(max_length = 75, verbose_name="Last Name")

vjk/forms.py
from django import forms
from django.forms import ModelForm
from .models import Student

class StudentForm(ModelForm):

	# Define the form with respect to Student Model
	class Meta:
		model = Student
		# Use all student fields in form
		fields = '__all__'

vjk/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader, Context
from django.core import mail
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Contact, Donor, Sponsor, Student, Volunteer, Contribution
from .forms import StudentForm
from django.contrib import messages

@login_required(login_url='/admin/login/', redirect_field_name='redirect')
def index(request):
    contacts            = Contact.objects.all()
    contact_fields      = Contact._meta.get_fields()[5:]
    donors              = Donor.objects.all()
    donor_fields        = Donor._meta.get_fields()[2:]
    sponsors            = Sponsor.objects.all()
    sponsor_fields      = Sponsor._meta.get_fields()[2:]
    students            = Student.objects.all()
    student_fields      = Student._meta.get_fields()[1:]
    volunteers          = Volunteer.objects.all()
    volunteer_fields    = Volunteer._meta.get_fields()[2:]
    contributions       = Contribution.objects.all()
    contribution_fields = Contribution._meta.get_fields()[1:]

    context = {
            "request": request,
            "contacts": contacts,
            "contact_fields" : contact_fields,
            "donors": donors,
            "donor_fields": donor_fields,
            "sponsors": sponsors,
            "sponsor_fields": sponsor_fields,
            "students": students,
            "student_fields": student_fields,
            "volunteers": volunteers,
            "volunteer_fields": volunteer_fields,
            "contributions": contributions,
            "contribution_fields": contribution_fields
     }
    return render(request, 'vjk/index_features.html', context)


def student_form(request):
    if request.method == 'POST':
        # create form instance and populate with data from request
        form = StudentForm(request.POST)
        if form.is_valid():
            # If valid form, create student model from data
            form.save() 
            return redirect('/success')
        else:
            messages.warning(request, 'Whoops, something went wrong.')

    else:
        form = StudentForm()

    return render(request, 'vjk/studentform.html', {'form': form})

def success(request):
    return render(request, 'vjk/success.html')

vjk/templates/vjk/base.html
<!-- Base html file for vjk site from which everything else inherits --> 

<!-- Load static and scripts -->
{% load static %}
{% include 'vjk/partials/scripts.html' %}

<html>
<head>
 	<!-- Load head personal to individual page (if any)-->
 	{% block head %} {% endblock %}
</head>
<body>
	<!-- Body -->
	{% block body %}{% endblock %}

	<!-- Footer -->
	<div id='container'>
	{% include 'vjk/partials/footer.html' %}
	</div>
</body>
</html>

vjk/templates/vjk/index.html
{% extends 'vjk/base.html' %}


{% block head %}
  <title>Search Page</title>
  <!-- Load Scripts  -->
  {% block scripts %} {% endblock %}
{% endblock %}

{% block body %}
  <div class="container-fluid">
    {% block header %} {% endblock %}

    <div class="container options">
      {% block options %} {% endblock %}
    </div>

    <div class="all">
      <!-- CONTACTS -->
      {% block contacts %} {% endblock %}

      <!-- DONORS -->
      {% block donors %} {% endblock %}
      
      <!-- SPONSORS -->
      {% block sponsors %} {% endblock %}
        
      <!-- STUDENTS  -->
      {% block students %} {% endblock %}

      <!-- VOLUNTEERS  -->
      {% block volunteers %} {% endblock %}

      <!-- CONTRIBUTIONS  -->
      {% block contributions %} {% endblock %}
    </div>

  </div>
{% endblock %}

vjk/templates/vjk/index_features.html
{% extends "vjk/index.html" %}
{% load static %}

{% block scripts %}
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'vjk/style.css' %}">
 -->
 <script type="text/javascript" src="{% static 'search.js' %}"></script>
<script type="text/javascript" src="{% static 'tableschange.js' %}"></script>
<script type="text/javascript" src="{% static 'optionschange.js' %}"></script>
<script type="text/javascript" src="{% static 'email.js' %}"></script>
{% endblock %}


{% block header %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-brand">VJK Database</p>
    </div>
     <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'admin:index' %}">Back to Admin Page</a></li>
      <li><a href="{% url 'admin:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block options %}
<div class="container">
	<div class="container col-sm-6">
		<h3>Table: 
		  <select id="table">
		    <option value="contacts">Contacts</option>
		    <option value="donors">Donors</option>
		    <option value="sponsors">Sponsors</option>
		    <option value="students">Students</option>
		    <option value="volunteers">Volunteers</option>
		    <option value="contributions">Contributions</option>
		  </select>
		</h3>
	</div>
	<div class="container search col-sm-6"> 
		<input id="input" type="text" placeholder="Search" onsubmit="initiateSearch">
		<select id="field">
		  <option value="all">Anything</option>
		  <option value="First Name">First Name</option>
		  <option value="Last Name">Last Name</option>
		  <option value="Email">Email</option>
		  <option value="Phone">Phone</option>
		</select>
		<input id="submit" type="button" class="btn" value="Search"></input>
	</div>
</div>

<div class="email container col-sm-12">
	<input id="download" type="button" class="btn" value="Copy Selected Email Addresses">
		<!-- <img src="{% static 'vjk/clippy.svg' %}" alt="Copy to clipboard"> -->
		<button id="emailButton" class="btn" data-clipboard-text="Nothing!" hidden> 
		</button>
	</input>
	<br>
	<input id="selectEverything" type="button" class="btn" value="Select All Email Addresses (All Categories)"></input>
	<hr>
</div>



{% csrf_token %}
{% endblock %}

{% block contacts %}
<div class="contacts-div">
<h3 class="model-name">Contacts</h3>
{% if contacts %}
<table id="contacts" class="table">
  <tr>
    <th>Select All<br><input type="checkbox" id="selectAllContacts"></input></th>
    {% for field in contact_fields %}
      <th>{{ field.verbose_name }}</th>
    {% endfor %}
  </tr>
  {% for contact in contacts %}
    <tr id="contact{{contact.id}}Row" class="contactRow">
        <td><input id="contact{{contact.id}}" class="checkboxContact" type="checkbox" name="checks" value="<{{contact.email}}>"></input></td>
    {% for value in contact %}
      <td>{{ value }}</td>
  {% endfor %}
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No Contact data are available.</p>
{% endif %}
<hr>
</div>
{% endblock %}

{% block donors %}
<div class="donors-div" hidden>
<h3 class="model-name">Donors</h3>
{% if donors %}
<table id="donors" class="table">
  <tr>
    {% for field in donor_fields %}
      <th>{{ field.verbose_name }}</th>
    {% endfor %}
  </tr>
  {% for donor in donors %}
  <tr class="donorRow">
    {% for value in donor %}
      <td>{{ value }}</td>
    {% endfor %}
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No Donor data are available.</p>
{% endif %}
<hr>
</div>
{% endblock %}

{% block sponsors %}
<div class="sponsors-div" hidden>
	<h3 class="model-name">Sponsors</h3>
	{% if sponsors %}
	<table id="sponsors" class="table">
	  <tr>
	    {% for field in sponsor_fields %}
	      <th>{{ field.verbose_name }}</th>
	    {% endfor %}
	  </tr>
	  {% for sponsor in sponsors %}
	  <tr class="sponsorRow">
	    {% for value in sponsor %}
	      <td>{{ value }}</td>
	    {% endfor %}

	  </tr>
	  {% endfor %}
	</table>
	{% else %}
	<p>No Sponsor data are available.</p>
	{% endif %}
	<hr>
</div>
{% endblock %}

{% block contributions %}
<div class="contributions-div" hidden>
	<h3 class="model-name">Contributions</h3>
	{% if contributions %}
	<table id="contributions" class="table">
	  <tr>
	    {% for field in contribution_fields %}
	      <th> {{ field.verbose_name }} </th>
	    {% endfor %}
	  </tr>
	  {% for contribution in contributions %}
	  <tr class="contributionRow">
	    {% for value in contribution %}
	      <td>{{ value }}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</table>
	{% else %}
	<p>No Contribution data are available.</p>
	{% endif %}
	<hr>
</div>
{% endblock %}

{% block students %}
	<div class="students-div" hidden>
	<h3 class="model-name">Students</h3>
	{% if students %}
	<table id="students" class="table">
	  <tr>
	    <th>Select All<br><input type="checkbox" id="selectAllStudents"></input></th>
	    {% for field in student_fields %}
	      <th>{{ field.verbose_name }}</th>
	    {% endfor %}

	  </tr>
	  {% for student in students %}
	  <tr id="student{{student.id}}Row" class="studentRow">
	    <td><input id="student{{student.id}}" class="checkboxStudent" type="checkbox" name="checks" value="<{{student.email}}>"></td>
	    {% for value in student %}
	      <td>{{ value }}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</table>
	{% else %}
	<p>No Student data are available.</p>
	{% endif %}
	<hr>
</div>
{% endblock %}

{% block volunteers %}
<div class="volunteers-div" hidden>
	<h3 class="model-name">Volunteers</h3>
	{% if volunteers %}
	<table id="volunteers" class="table">
	  <tr>
	    <th>Select All<br><input type="checkbox" id="selectAllVolunteers"></input></th>
	    {% for field in volunteer_fields %}
	      <th>{{ field.verbose_name }}</th>
	    {% endfor %}
	  </tr>
	  {% for volunteer in volunteers %}
	  <tr id="volunteer{{volunteer.id}}Row" class="volunteerRow">
	    <td><input id="volunteer{{volunteer.id}}" class="checkboxVolunteer" type="checkbox" name="volun" value="<{{volunteer.email}}>"></td>
	    {% for value in volunteer %}
	      <td>{{ value }}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</table>
	{% else %}
	<p>No Volunteer data are available.</p>
	{% endif %}
</div>
{% endblock %}

vjk/templates/vjk/studentform.html
{% extends 'vjk/index.html' %}
{% load bootstrap3 %}

{% block body %}
<div class='container student-form'>
	<h3>Hello! Please enter your information. </h3>
	<div class='col-sm-8 col-sm-offset-2'>
		<form method="post">
		    {% csrf_token %}
		    {% bootstrap_form form %}
		    <button type="submit" class='save btn btn-primary'>
		    	Submit
		    </button>
		</form>
	</div>
</div>
{% endblock %}

vjk/templates/vjk/success.html
{% extends 'vjk/index.html' %}

{% block body %}
<div class='container text-center'>
	<h3>Thank you for registering!</h3>
	<a href="{% url 'vjk:index' %}" class='btn btn-primary'>Return to Index</a>
</div>
{% endblock %}